### PR TITLE
Update to PlanetaryEphemeris v0.7

### PR DESCRIPTION
**Pull request by PerezHz**
I’m opening this PR to join efforts to update to PE v0.7. We should be now in a position to update the ephemeris in LuEdRaMo/sseph and proceed to the corresponding changes here.

cc: @lbenet @LuEdRaMo

### CODE REVIEW

**Comment by LuEdRaMo** [comment]
`LuEdRaMo/sseph` has been updated to PE v0.7 ephemeris, so we have green flag to start this PR.

**Comment by LuEdRaMo** [comment]
With the last commit, propagation methods now work with PE v0.7 and with precomputed accelerations and newtonian potentials, so this PR should solve https://github.com/PerezHz/NEOs.jl/issues/17. Also, `propagate` and `propagate_root` now use `taylorinteg` instead of `neosinteg`. Currently, `propagate_root` cannot undergo the same change since root-finding `taylorinteg` has no dense output option.

**Comment by lbenet** [comment]
There are some changes coming in TaylorIntegration; see https://github.com/PerezHz/TaylorIntegration.jl/pull/168. Could you have a look if everything works smoothly?

**Comment by PerezHz** [comment]
> With the last commit, propagation methods now work with PE v0.7 and with precomputed accelerations and newtonian potentials, so this PR should solve https://github.com/PerezHz/NEOs.jl/issues/17. Also, propagate and propagate_root now use taylorinteg instead of neosinteg. Currently, propagate_root cannot undergo the same change since root-finding taylorinteg has no dense output option.

Many thanks for this change!

**Comment by PerezHz** [comment]
> Currently, propagate_root cannot undergo the same change since root-finding taylorinteg has no dense output option.

Then maybe I could update https://github.com/PerezHz/TaylorIntegration.jl/pull/168 to include the missing feature? What do you guys think?

**Comment by PerezHz** [comment]
Heads up: I pushed a couple of commits updating the artifacts

**Comment by PerezHz** [comment]
It seems the MPC website is not fond of receiving requests from `Downloads.curl`... I'll try to take a look into this

**Comment by PerezHz** [comment]
Just retriggered CI... good news is, when the download issues don't get in the way, tests actually pass!

**Comment by lbenet** [comment]
> Then maybe I could update https://github.com/PerezHz/TaylorIntegration.jl/pull/168 to include the missing feature? What do you guys think?

While I agree to update https://github.com/PerezHz/TaylorIntegration.jl/pull/168, what do you have in mind? More concretely, the question is: which time shall we associate with the (dense output) polynomials, the crossing time (actual Poincare surface crossing, or root of the function `g`), or the previous time, which includes the crossing as well? 

Note that when doing jet transport, the time of crossing is actually a polynomial in the jet transport coordinates.

In any case, if you have a concrete idea, go ahead a push a commit...

**Comment by PerezHz** [comment]
Sorry, I pushed two commits which I meant to push to another branch; it's now fixed... 😓

**Comment by PerezHz** [comment]
> While I agree to update https://github.com/PerezHz/TaylorIntegration.jl/pull/168, what do you have in mind?

Since the root-finding times are well-defined without the dense output, for the root-finding method with dense output, my first idea for root-finding with dense ouput would be to follow as closely as possible the root-finding method of `taylorinteg` without dense output. But I'm not sure if that's consistent with `propagate_root` here...

**Comment by PerezHz** [comment]
I ran the tests from this branch of NEOs.jl together with the PerezHz/TaylorIntegration.jl#168 branch, and I got some errors in PE due to some assertions in interpolation. Those can be fixed quick, but maybe it makes more sense to actually merge the PR#168 in TI essentially as it is now, and then patch things if/when necessary. This way we can track compatibility, etc., with CI. Regarding the `taylorinteg`  method with root-finding and dense output, I can take care of that in a separate PR in TI.

**Comment by lbenet** [comment]
I agree; go ahead and merge https://github.com/PerezHz/TaylorIntegration.jl/pull/168, and either we skip that test in Julia nightly, of somehow fix it.

**Comment by PerezHz** [comment]
I think the only thing pending here is to add the root-finding with dense ouput ` taylorinteg` method instead of calling `neosinteg` in ` propagate_root` ; I'm on it and will hopefully have some time later today to push a new PR in TaylorIntegration

**Comment by PerezHz** [comment]
Update: [PerezHz/TaylorIntegration#170](https://github.com/PerezHz/TaylorIntegration.jl/pull/170) has been merged and TI v0.14.1 has been released; I updated this PR with the corresponding changes, the most important one being `neosinteg` is no more... Time for Saturn to eat his children I guess 😅

**Comment by PerezHz** [comment]
This is now ready for review @LuEdRaMo @lbenet

**Review by lbenet — COMMENTED** [review]
Thanks @PerezHz for this PR. In general things LGTM.

While we have green lights, I wonder if you have checked some results (e.g., Apophis) using this PR in comparison to the old ones? I'm in favor of merging this, but prefer to do it once we have an independent check.

**Comment by PerezHz** [comment]
> I wonder if you have checked some results (e.g., Apophis) using this PR in comparison to the old ones? I'm in favor of merging this, but prefer to do it once we have an independent check.

I agree that we should have an independent check; I'll run this PR on Apophis and will report back!

**Comment by PerezHz** [comment]
Update: I removed now-unused the non-threaded asteroid dynamical model, which was really useful back in the day when to debug the multi-threaded version. Another change I did was to transition from `SatelliteToolbox` to `SatelliteToolboxTransformations`, a lightweight dependency which has the whole functionality we actually need for the ECEF <-> ECI transformations. I can report that offline tests show that this PR together with the latest releases of PE and TI can reproduce the results from our paper, including the Yarkovsky transverse parameter A2 together with the associated uncertainties and post-fit statistics (normalized RMS, chi-squared, etc.). There are some minor updates pending related to some scripts and notebooks, but all in all I think we can go ahead and merge this PR, since the update to PE v0.7 is complete at last!

**Pull request merged**
