### PR TITLE
Some aesthetic fixes

### PR DESCRIPTION
**Pull request by PerezHz**
@LuEdRaMo this can help solve the file permissions mode change (100644 → 100755) that is seen in some of the diffs in #31, i.e., this PR switches back from 755 to 644, as files are currently in main. This PR also changes back to linux-style end of line sequence (LF), instead of windows-style end of line sequence (CRLF). Also, I have trimmed trailing whitespaces where appropriate. I also added a test on NEOParameters, with the corresponding fix that I suggested in one of my recent comments. I opted to open this PR instead of pushing directly to the `lerm/gaussinitcond` branch, just to avoid interfering with your work on #31.

### CODE REVIEW

**Comment by PerezHz** [comment]
EDIT: updated the original PR comment to reflect the fact that mode changes correspond to file permission mode (and not to end of line sequences, as stated previously). That is, this PR updates file permissions mode, end of line sequences and trims trailing whitespaces.

**Comment by LuEdRaMo** [comment]
Thanks @PerezHz for this PR. I am preparing some changes in https://github.com/PerezHz/NEOs.jl/pull/31, so I'll wait until those are ready to merge this.

**Comment by PerezHz** [comment]
> Thanks @PerezHz for this PR. I am preparing some changes in https://github.com/PerezHz/NEOs.jl/pull/31, so I'll wait until those are ready to merge this.

Sounds great! Feel free to ping me here so that I can update this PR after you push your latest changes there

**Comment by LuEdRaMo** [comment]
Hi @PerezHz, the changes in https://github.com/PerezHz/NEOs.jl/pull/31 are ready; if we update this branch I think we can merge this.

**Comment by PerezHz** [comment]
> Hi @PerezHz, the changes in https://github.com/PerezHz/NEOs.jl/pull/31 are ready; if we update this branch I think we can merge this.

Just did the update, this should be ready to go 👍

**Comment by PerezHz** [comment]
After checking the diff between this branch and #31 I found I changed some tests that I didn't mean to (changes ; just fixed those in the last commit so now the diff is looking good. This is now ready to merge.

**Comment by LuEdRaMo** [comment]
Thanks again @PerezHz, I'll proceed to merge.

**Pull request merged**
